### ISSUE TITLE
运行wepon/sesson one/extract_feature.py出现错误

### ISSUE THREAD

**Issue by gutsttt** [wepe/O2O-Coupon-Usage-Forecast#13]
你好 我是新人 想学习一下你的代码 运行extract_feature.py出现问题 报错如下
Traceback (most recent call last):
  File "extract_feature.py", line 60, in <module>
    feature3 = off_train[((off_train.date>='20160315')&(off_train.date<='20160630'))|((off_train.date=='null')&(off_train.date_received>='20160315')&(off_train.date_received<='20160630'))]
  File "C:\Users\u\AppData\Roaming\Python\Python36\site-packages\pandas\core\ops.py", line 879, in wrapper
    res = na_op(values, other)
  File "C:\Users\u\AppData\Roaming\Python\Python36\site-packages\pandas\core\ops.py", line 818, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison
想请问该怎么处理

**Comment by whiteyyc** [comment]
你好，我也是新手，遇到这个问题，你解决了吗？

**Comment by jijeng** [comment]
on_train = pd.read_csv('data/ccf_online_stage1_train.csv',header=None, keep_default_na=False)
在使用pd 读取csv的时候 加上参数 keep_default_na = False

**Comment by RobertMarton** [comment]
Not work...My python version is 2.7

**Comment by ChenKevin0123** [comment]
类型错误，改下字段类型

**Comment by xxcheng0708** [comment]
off_train.date and off_train.date_received is float type
