### ISSUE TITLE
运行wepon/sesson one/extract_feature.py出现错误

### ISSUE THREAD

**Issue by aojue1109** [wepe/O2O-Coupon-Usage-Forecast#15]
我是新手一枚，运行出现：
Traceback (most recent call last):
  File "D:/pythonCode/PycharmProjects/O2O-Coupon-Usage-Forecast/code/wepon/season one/extract_feature.py", line 97, in <module>
    t3['this_month_user_receive_same_coupon_lastone'] = t3.max_date_received - t3.date_received
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 721, in wrapper
    result = wrap_results(safe_na_op(lvalues, rvalues))
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 682, in safe_na_op
    return na_op(lvalues, rvalues)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 664, in na_op
    result[mask] = op(x[mask], _values_from_object(y[mask]))
TypeError: unsupported operand type(s) for -: 'float' and 'str'
看了几个issue的问题都一样，但没有找到能够解决问题的方案，希望能够得到解答，万分感谢

**Comment by aojue1109** [comment]
自行跳坑成功，原来是t3的第一行数据有问题，下面计算的时候不能选取第一行。
t3 = t3[1:]
t3['this_month_user_receive_same_coupon_lastone'] = t3.max_date_received.astype('float') - t3.date_received.astype('float')
t3['this_month_user_receive_same_coupon_firstone'] = t3.date_received.astype('float')- t3.min_date_received.astype('float')

大致这样处理既可以把第一行的数据去除掉，后面计算的时候就可以了
