### ISSUE TITLE
运行wepon/sesson one/extract_feature.py错误

### ISSUE THREAD

**Issue by BoyuanJiang** [wepe/O2O-Coupon-Usage-Forecast#2]
Traceback (most recent call last):
  File "extract_feature.py", line 99, in <module>
    t3['this_month_user_receive_same_coupon_lastone'] = t3.max_date_received - t3.date_received
  File "/usr/lib64/python2.7/site-packages/pandas/core/ops.py", line 715, in wrapper
    result = wrap_results(safe_na_op(lvalues, rvalues))
  File "/usr/lib64/python2.7/site-packages/pandas/core/ops.py", line 676, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/usr/lib64/python2.7/site-packages/pandas/core/ops.py", line 658, in na_op
    result[mask] = op(x[mask], _values_from_object(y[mask]))
TypeError: unsupported operand type(s) for -: 'float' and 'str'

**Comment by wepe** [comment]
你把line99换成这个试试

```python
t3['this_month_user_receive_same_coupon_lastone'] = t3.max_date_received.astype('int') - t3.date_received.astype('int')
```

**Comment by BoyuanJiang** [comment]
@wepe  
改了后得到了以下的错误
Traceback (most recent call last):
  File "extract_feature.py", line 99, in <module>
    t3['this_month_user_receive_same_coupon_lastone'] = t3.max_date_received.astype('int') - t3.date_received.astype('int')
  File "/usr/lib64/python2.7/site-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/internals.py", line 3189, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/internals.py", line 3056, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/internals.py", line 461, in astype
    values=values, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas/core/internals.py", line 504, in _astype
    values = _astype_nansafe(values.ravel(), dtype, copy=True)
  File "/usr/lib64/python2.7/site-packages/pandas/types/cast.py", line 531, in _astype_nansafe
    raise ValueError('Cannot convert NA to integer')
ValueError: Cannot convert NA to integer

**Comment by wepe** [comment]
```
ValueError: Cannot convert NA to integer
```

你应该是date_received这一列数据有问题，我的可以跑通，你确定一下自己下载的数据没问题？ date_received字段的数据是 20160701 这种格式的。

**Comment by BoyuanJiang** [comment]
确定数据没有问题，
![image](https://cloud.githubusercontent.com/assets/16739780/21952391/ba61c1c8-da55-11e6-8aa6-40de9495aa16.png)
这个是执行line 99之前的t3的内容，我想会不会是我的pandas版本的问题，请问你的pandas的版本是多少？

**Comment by wepe** [comment]
我的pandas 版本：0.18.1

**Comment by BoyuanJiang** [comment]
确实是我的原始数据有些问题，谢谢

**Comment by CXY573** [comment]
@BoyuanJiang  你用的数据不是作者提供的数据吗，我也出现你这个错误了 请问怎么解决的

**Comment by aojue1109** [comment]
@BoyuanJiang 请问数据有什么问题，我也在这个点上出现了问题，不确定数据在哪里有问题
