### ISSUE TITLE
season one:特征提取代码有问题

### ISSUE THREAD

**Issue by OUCWIND** [wepe/O2O-Coupon-Usage-Forecast#4]
直接运行有错：
Traceback (most recent call last):
  File "/home/pzy/program/tianchi/test/extract_feature.py", line 99, in <module>
    t3['this_month_user_receive_same_coupon_lastone'] = t3.max_date_received - t3.date_received
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 715, in wrapper
    result = wrap_results(safe_na_op(lvalues, rvalues))
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 676, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 658, in na_op
    result[mask] = op(x[mask], _values_from_object(y[mask]))
TypeError: unsupported operand type(s) for -: 'float' and 'str'

是不是代码不是最终的

**Comment by Salomefu** [comment]
请问你解决了这个问题吗？

**Comment by CXY573** [comment]
@OUCWIND @Salomefu 你们解决了吗，我也是出现了这个错误

**Comment by wepe** [comment]
t3.max_date_received.astype(float) - t3.date_received.astype(float)

**Comment by CXY573** [comment]
@wepe 
Traceback (most recent call last):
  File "xgb.py", line 58, in <module>
    dataset3_preds.label = MinMaxScaler().fit_transform(dataset3_preds.label)#区间缩放到[0,1]
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 518, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 308, in fit
    return self.partial_fit(X, y)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 334, in partial_fit
    estimator=self, dtype=FLOAT_DTYPES)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py", line 410, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[-0.21156955  0.33369869 -0.30134243 ...,  0.08833629 -0.15614033
  0.31751922].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by CXY573** [comment]
@wepe 
运行xgb.py运行到后面后出现这个问题 是什么意思呢

**Comment by aojue1109** [comment]
@OUCWIND @wepe @CXY573 请问有解决吗，我也遇到这个问题
